version: '3'
services:
    web:
        depends_on:
            - app
        image: nginx:alpine
        tty: true
        volumes:
            - ./:/var/www
            - ./dev/nginx:/etc/nginx/conf.d
            - ./tmp/logs:/var/log/nginx
        ports:
            - '80:80'
    app:
        build:
            context: .
            dockerfile: ./dev/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
    db:
        image: postgres:14-alpine
        environment:
            POSTGRES_DB: main
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: secret
            POSTGRES_HOST_AUTH_METHOD: trust
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        ports:
            - "5432:5432"
volumes:
    db-data: